### PR TITLE
Updated install instructions for new users/Windows

### LINKED ISSUE #401: [Bug]: Install instructions produce an error on Windows
### Contact Details

_No response_

### What happened?

From both the Windows command line & PowerShell, the provided Docker install command throws an invalid character error. This is produced by the character used to stringify the pwd command (the command also being lacking on Windows). However, the Docker install will proceed normally on Windows with ./ substituted for `pwd`--I would suggest mentioning this in the install guide so Windows users unfamiliar with the command line aren't frustrated. 

### Flavor

Docker

### Version

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by beckyosb**
Fixes #401 by removing the invalid character & missing command that prevent the install command from running from the Windows command line.

### CODE REVIEW

**Comment by hkamran80** [comment]
Alternatively, you could change the original command to use `./` instead of the `pwd` command. Both do the same thing.

**Comment by beckyosb** [comment]
I assumed, I just opted on the side of being conservative! Either/or.

**Comment by beckyosb** [comment]
I simplified the install guide per @hkamran80 & added a link to the Docker install guide for users who might not be familiar.

**Comment by AnalogJ** [comment]
appreciate the doc updates @beckyosb these are super helpful! 

Merging 🥳

**Pull request merged**
